### ISSUE TITLE
Close button overlaps with status bar in iPhone X

### ISSUE THREAD

**Issue by annjawn** [hyperoslo/Lightbox#153] opened 2017-11-17 08:34 UTC
The close button is currently overlapping with the status bar in iPhone X which makes it inaccessible so swipe to dismiss is the only thing that works.

![image](https://user-images.githubusercontent.com/26977294/32937869-086c5da4-cb2f-11e7-947f-30922cd4e636.png)

**Comment by onmyway133** [comment] 2017-11-17 10:14
@annjawn Hi, thanks for reporting the issue. It maybe because we haven't used `safe area` when doing layout.

**Comment by onmyway133** [comment] 2017-11-17 15:23
@annjawn Hi, can you check https://github.com/hyperoslo/Lightbox/releases/tag/2.1.0 ?

**Comment by annjawn** [comment] 2017-11-17 18:14
Hi @onmyway133 , yes it's a safe area issue. I've been having a lot of trouble with safe area in my project and had to do multiple workarounds. There are issues with other libs that use controllers like this and I have raised issues and requested PRs with them and you are the only one who responded so fast and fixed it so thank you so much. 😃

**Comment by annjawn** [comment] 2017-11-17 18:20
@onmyway133 the latest update (2.1.0) is causing a crash at `InfoLabel.swift`

![image](https://user-images.githubusercontent.com/26977294/32962310-d751c07c-cb80-11e7-8f21-33fc1f24e5a4.png)

**Comment by onmyway133** [comment] 2017-11-18 22:12
@annjawn I think this was the problem with truncating text with emoji, however I can't reproduce it. Do you have any detailed steps that I can reproduce ?

**Comment by onmyway133** [comment] 2017-11-20 22:38
@annjawn Hi, it was because of this PR https://github.com/hyperoslo/Lightbox/pull/157 which was just merged into master. We will release new version soon. I will close this for now, as it was originally an issue regarding iPhone X

**Closed by onmyway133** 2017-11-20 22:38 UTC
