### ISSUE TITLE
SPM Support and Resources

### ISSUE THREAD

**Issue by yspreen** [hyperoslo/Lightbox#250] opened 2020-06-15 19:11 UTC
https://github.com/hyperoslo/Lightbox/blob/master/Resources/Lightbox.bundle/lightbox_play%402x.png

Did you check that this file is still working with SPM @Tobisaninfo ? Paging bc of #248 

See https://github.com/MessageKit/MessageKit/pull/1341#issuecomment-621670678

**Comment by Tobisaninfo** [comment] 2020-06-15 19:22
In Xcode, in the file tab under the Swift Package Dependencies, it seems that the asset is available

<img width="439" alt="Bildschirmfoto 2020-06-15 um 21 21 11" src="https://user-images.githubusercontent.com/5264563/84697272-24ec5780-af4e-11ea-832f-c687bbf9d423.png">

But I'm not sure how to test this in code. May you can provide some example that I can test in my app.

**Comment by yspreen** [comment] 2020-06-15 20:59
Yes, because that list just mirrors the repo contents. But similarly to the Readme file and other additional content, it's not actually bundled into the app. Can you try adding a video to your lightboxes to see if the play button is there?

**Comment by Tobisaninfo** [comment] 2020-06-16 08:39
Oh yes, you are right, I tried to get this working by copy the resource into the sources and try to figure out if there exists any hint in the apple documentation, but I failed. I guess we have to wait until apple adds some capabilities to the SwiftPM.

**Comment by yspreen** [comment] 2020-06-16 13:56
It might be best to add this info to the readme, or just remove Package.swift for now...

**Comment by yspreen** [comment] 2020-06-16 13:56
There's a lot of resources on this, because it's the main reason why most big libraries don't have SPM support. Swift 5.3 is supposed to solve this, but there is no ETA.

**Comment by Tobisaninfo** [comment] 2020-06-16 14:53
I think the best is adding this to the readme, removing the SwiftPM for know means, that you cannot use SwiftPM or Carthage, the only ways would be CocoaPods or building a version manual.

**Comment by yspreen** [comment] 2020-06-16 14:55
I'm using carthage and it works great for me, independent of SPM

**Comment by Tobisaninfo** [comment] 2020-06-16 14:57
Oh I see, you changed the Cartfile yesterday. I had on Sunday some trouble with it caused by hyperoslo/Imaginary and that was my motivation it add the SwiftPM to this project

**Comment by yspreen** [comment] 2020-06-16 14:59
The carthage dependency issue is resolved now. imo SPM comes with too many caveats for now, so before Swift 5.3 is out I'd be in favor of removing it

**Comment by 3lvis** [comment] 2020-06-22 13:16
Should be working now, although only under iOS 13.

**Comment by Tobisaninfo** [comment] 2020-06-22 13:20
Using the SFSymbols seems to be a good thing, even it is currently only working on iOS 13.

We will see, what Apple will present is week for Swift and SwiftPM...

**Comment by 3lvis** [comment] 2020-06-22 13:24
I believe iOS 13 might be working on most devices. Another alternative is under iOS 13 to use an ASCII symbol.

**Comment by 3lvis** [comment] 2020-06-27 04:42
Closing for now since we have a workaround until Xcode 12 helps with this.

**Closed by 3lvis** 2020-06-27 04:42 UTC
