### ISSUE TITLE
Not working in iOS 13. App getting Freeze.

### ISSUE THREAD

**Issue by darshit261991** [hyperoslo/Lightbox#236] opened 2019-10-07 10:46 UTC
Application getting freeze in iOS 13. Not able to open gallery of images.

**Comment by marcelosalloum** [comment] 2019-10-08 22:42
Same here

**Comment by marcelosalloum** [comment] 2019-10-08 22:46
This is actually a duplicate of https://github.com/hyperoslo/Lightbox/issues/229

**Comment by jespercr** [comment] 2019-10-14 21:14
Works as above for .fullScreen, but would love for it to work for .pageSheet/automatic as well in order to get consistency across the UI. Any update on this? Thanks a lot!

**Comment by dimidrollko** [comment] 2019-10-31 08:37
I think pod should be reworked. Right now faster approach to work with this lib is removing custom transition. 
  lazy var transitionManager: LightboxTransition = LightboxTransition()
After removing it you can present easily controller without freezing app after it dismiss.

**Comment by sudhakar-varma** [comment] 2019-12-17 11:42
> Works as above for .fullScreen, but would love for it to work for .pageSheet/automatic as well in order to get consistency across the UI. Any update on this? Thanks a lot!

thanks a lot. saved my day

**Comment by josjevv** [comment] 2020-03-02 10:28
I managed to get it working by using `.fullscreen` and disabling the transitionManager by inheriting from `LightboxController` and adding the following code:

```
    override public func viewDidLoad() {
        super.viewDidLoad()
        
        // Unset transitioning as this causes freezes
        // most probably related to automatic modals in iOS 13
        self.transitioningDelegate = nil
    }
```

**Comment by ReticentJohn** [comment] 2020-03-11 21:53
After pulling my hair out over this for a day was able to locate a workaround within the delegate:

Replace `guard let fromView = transitionContext.view(forKey: UITransitionContextViewKey.from),
        let toView = transitionContext.view(forKey: UITransitionContextViewKey.to)`

with the following `guard let fromView = transitionContext.viewController(forKey: .from)?.view,
        let toView = transitionContext.viewController(forKey: .to)?.view`

in LightboxTransition.swift. There's an open radar for this bug introduced in iOS 13 where custom animated transitioning delegates are failing to deliver target from/to views on anything other than `.fullscreen` for modals http://www.openradar.me/radar?id=4999313432248320

I won't open a PR for this as its a workaround and not recommended by documentation, but it worked for my purposes today more so than getting rid of the delegate altogether. This way you can preserve the nifty interactive dismiss.

**Comment by cmcnab** [comment] 2020-04-29 15:44
@ReticentJohn 's answer almost worked for me, but when presented over a .pageSheet/.automatic modal, it was removing the view beneath when dismissed.  It did get me wondering though, what if the nil from or to views just shouldn't be added to the transition container?  (Versus guarding that both must be present.)  I tried that and the following changes to that delegate seem to work in both cases for me:
```
  func animateTransition(using transitionContext: UIViewControllerContextTransitioning) {
    let container = transitionContext.containerView

    let fromView = transitionContext.view(forKey: UITransitionContextViewKey.from)
    let toView = transitionContext.view(forKey: UITransitionContextViewKey.to)

    let firstView = dismissing ? toView : fromView
    let secondView = dismissing ? fromView : toView

    if !dismissing { transition(false) }

    if let firstView = firstView {
        container.addSubview(firstView)
    }

    if let secondView = secondView {
        container.addSubview(secondView)
    }

    toView?.frame = container.bounds
    ...
```

**Closed** 2020-06-07 06:36 UTC

**Comment by mrJakez** [comment] 2021-02-18 20:19
Thank you guys - your comments saved me some hours :)
