### ISSUE TITLE
It hides shadow line under navbar

### ISSUE THREAD

**Issue by billypap1** [hyperoslo/Lightbox#245] opened 2020-05-24 21:41 UTC
When I close Lightbox and return to Main Screen, the line (shadow) under navbar has been removed. Is that a bug?

**Comment by 3lvis** [comment] 2020-06-07 06:36
Could you try again with the latest version, please?

**Comment by 3lvis** [comment] 2020-06-08 23:49
Closing for lack of answer.

**Comment by billypap1** [comment] 2020-06-13 11:36
How can I install version in master from pod file?

**Comment by 3lvis** [comment] 2020-06-14 02:12
@billypap1 This might be helpful https://guides.cocoapods.org/using/using-cocoapods.html

**Comment by billypap1** [comment] 2020-06-14 11:10
@3lvis I know how to install pods in my project. I don't know how can I install the master branch.
Something like that -> pod 'Lightbox', '~> Master' ?

**Comment by billypap1** [comment] 2020-06-14 11:45
@3lvis Ok, I installed these dependencies: 
pod 'Cache', :git => 'https://github.com/hyperoslo/Cache.git', :tag => '5.3.0'
pod 'Imaginary', :git => 'https://github.com/hyperoslo/Imaginary.git', :tag => '4.3.1'
pod 'Lightbox', :git => 'https://github.com/hyperoslo/Lightbox.git', :branch => 'master'

But didn't fixed the problem, when I close Lightbox Viewer and return to Main Screen, the line (shadow) under navbar has been removed.

**Comment by 3lvis** [comment] 2020-06-15 17:28
Damn. Would you mind sharing a small video, please?

**Comment by billypap1** [comment] 2020-06-15 19:21
No, sorry I can't because it is a private project.
To understand better, the flow is: 
Main Screen (select tableview cell) -> open Product Screen -> open Image in LightBox. 
Close Lightbox -> Return to MainScreen. The navbar shadow has been disappearred.
Have you include something like that in your code (on viewWillDisappear) ? 

`self.navigationController?.navigationBar.shadowImage = UIImage()
`
Your project works perfect in ios 13 (fullscreen mode and dynamic background) my only problem is with the navbar's shadow.

**Comment by billypap1** [comment] 2020-06-15 19:31
I just noticed an other related issue, it doesn't hide only navbar's shadow, it hides the titles in navigationController in any other Screen I navigate.
So there is a problem with navbar, not only the navbar's shadow.

**Comment by 3lvis** [comment] 2020-06-22 13:23
I'm not able to reproduce. I've added a navigation controller to the demo and works fine. https://github.com/hyperoslo/Lightbox/commit/ed69a9fdeeab9b432a59450c2f48e5ad2532ee80

If we can reproduce it could look into it, otherwise is hard to know what it's happening.

**Comment by sarbogast** [comment] 2020-06-24 12:02
There is definitely something freaky going on. I don't know if it is related to navigation controllers, but the fact of the matter is that I am presenting a LightboxController from within a UIViewController that is deep in the viewControllers of a UINavigationController, and I see several weird things happening:
- it doesn't present full screen like I would expect it to
- when I click the close button, it doesn't dismiss
- when I slide it down, it disappears but then my application is not responsive anymore, as if some view in front was swallowing touch events

Here is a short video that demonstrates the issue: https://d.pr/v/oRZJeW

Note that I'm running iOS 13.5 on an iPhone 11 Pro emulator in this video

**Comment by 3lvis** [comment] 2020-06-25 04:54
Can you try adding a `.modalPresentationStyle`?

https://github.com/hyperoslo/Lightbox/commit/25e4877614dcb9cc3151e94007e098c54ad92f47

**Comment by DevSana97** [comment] 2020-07-06 06:58
> https://d.pr/v/oRZJeW

same happens for me. :(

**Comment by DevSana97** [comment] 2020-07-06 07:04
> @sarbogast
> 
> Can you try adding a `.modalPresentationStyle`?
> 
> [25e4877](https://github.com/hyperoslo/Lightbox/commit/25e4877614dcb9cc3151e94007e098c54ad92f47)

Thanks man! This works fine :)

**Closed** 2020-07-10 00:46 UTC

**Comment by 3lvis** [comment] 2020-07-10 00:52
Fix published in 2.4.2, thanks! 

https://github.com/hyperoslo/Lightbox/releases/tag/2.4.2

------------

##### Finding this project helpful? Consider supporting further development and support by becoming a sponsor:
##### 👉  https://github.com/sponsors/3lvis
